import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box, Flex, Heading, Text, VStack } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { useGetPageBySlug, useGetPages } from "@/hooks";
import { getPageBySlug } from "@/contentful";
import { Page } from "@/models";
import { Form } from "@/components";


interface Props {
  locale: string;
  altLocale: string;
  locales: string[];
  title: string;
}


export default function AssociationRules(props: Props) {

  const { locale, locales, altLocale, title } = props;

  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(true)

  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form 
        action="http://127.0.0.1:5000/association_rules"
      />    

    </>
  );
}


export async function getStaticProps(props: Props){
  const { locale, locales } = props;

  const slug = 'association-rules';

  const { title } = await getPageBySlug(slug,locale);


  const [ altLocale ] = locales.filter(lang => lang !== locale);

  return {
    props: {
      ...props,
      altLocale,
      title
    
    }
  }
}