import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box, Text, VStack } from "@chakra-ui/react";
import { useEffect, useState } from "react";


interface Props {
  locale: string;
  altLocale: string;
  locales: string[];
}


export default function Home() {

  const [data, setData] = useState<any>(null);

  useEffect(() => {
    fetch('/api/')
      .then(response => response.json())
      .then(data => setData(data))
      .catch(error => console.error('Error al hacer la solicitud:', error));
  }, []);



  return (
    <>
      <Head>
        <title>Ganbaty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <Text as="h1">Datos de la API:</Text>
        {data ? (
          <Text as="pre">{JSON.stringify(data, null, 2)}</Text>
        ) : (
          <Text as="p">Cargando...</Text>
        )}
      </VStack>
    </>
  );
}

export async function getStaticProps(props: Props){
  const { locale, locales } = props;

  const [ altLocale ] = locales.filter(lang => lang !== locale);

  return {
    props: {
      ...props,
      altLocale
    }
  }
}