import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box, Flex, Heading, Text, VStack } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { useGetPageBySlug, useGetPages, useGetTools } from "@/hooks";
import { getPageBySlug, getPageContent } from "@/contentful";
import { Page } from "@/models";
import { PageContentLayout } from "@/layout";


interface Props {
  locale: string;
  altLocale: string;
  locales: string[];
  title: string;
  content: any;
}


export default function Home(props: Props) {

  const { locale, locales, altLocale, title, content } = props;


  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContentLayout {...props} /> 


      
    </>
  );
}


// export async function getStaticPaths(){
//   const posts = await getPostsSlugs();

//   const pathES = posts.map(( item ) => ({
//           params: {
//               slug: [item.slug]
//           },
//           locale: 'es'
//       })
//   )

//   const pathEN = posts.map(( item ) => ({
//           params: {
//               slug: [item.altSlug]
//           },
//           locale: 'en-US'
//       })
//   )
      
//   const allPaths = [ ...pathEN, ...pathES ];
      
//   return {
//       paths: allPaths,
//       fallback:true
//   }
// }   



export async function getStaticProps(props: Props){
  const { locale, locales } = props;

  const slug = locale === 'es' ? 'inicio' : 'home';

  const { title } = await getPageBySlug(slug,locale);

  const content = await getPageContent(slug,locale);

  console.log(content)

  const [ altLocale ] = locales.filter(lang => lang !== locale);

  return {
    props: {
      ...props,
      altLocale,
      title,
      content
    }
  }
}